// svelte/src/App.svelte
<script lang="ts">
    import { Route, Router } from "svelte-routing";
    import NavBar from "./lib/NavBar/NavBar.svelte";
    import NavBarButton from "./lib/NavBar/NavBarButton.svelte";
    import NotFound from "./pages/NotFound.svelte";
    import Home from "./pages/Home/Home.svelte";
    import News from "./pages/News.svelte";
    import NewsArticle from "./pages/NewsArticle.svelte";
    import Game from "./pages/Game.svelte";
    import Download from "./pages/Download.svelte";
    import Footer from "./lib/Footer/Footer.svelte";
    import FooterButton from "./lib/Footer/FooterButton.svelte";
    import { isMobile } from "./lib/screen-store";

    const homeRoute = "/";
    const newsRoute = "/news";
    const newsArticleRoute = "/news/:id";
    const gameRoute = "/game";
    const downloadRoute = "/download";
    const aboutRoute = "https://wagnrd.de";
    const impressumRoute = "/impressum";
    const privacyPolicyRoute = "/privacy";
    const defaultPixelRatio = 16 / 9;
    let innerWidth = Number.MAX_SAFE_INTEGER;

    function openForumsTab() {
        window.open("https://" + window.location.host + "/forums/");
    }

    function openEmail() {
        window.open("mailto:projects@wagnrd.de?subject=Y.A.T.D.%20support%20ticket");
    }

    function setMobileState(pageSize: number) {
        const pixelRatio = screen.width / screen.height;
        const mobileThreshold = 1 - (0.4 / defaultPixelRatio * pixelRatio);

        if (pageSize <= screen.width * mobileThreshold ||
            window.matchMedia("screen and (max-device-width: 1000px)").matches) {
            isMobile.update(_ => true);
        } else {
            isMobile.update(_ => false);
        }
    }

    $: setMobileState(innerWidth);
</script>

<svelte:window bind:innerWidth={innerWidth}/>
<main class:mobile={$isMobile}>
    <NavBar homeRoute={homeRoute}>
        <NavBarButton route={newsRoute}>NEWS</NavBarButton>
        <NavBarButton route={gameRoute}>GAME</NavBarButton>
        <NavBarButton onClick={openForumsTab}>FORUMS</NavBarButton>
        <NavBarButton route={downloadRoute}>DOWNLOAD</NavBarButton>
    </NavBar>

    <div id="flex-wrapper">
        <Router>
            <Route path={homeRoute} component={Home}/>
            <Route path={newsRoute} component={News}/>
            <Route path={newsArticleRoute} component={NewsArticle}/>
            <Route path={gameRoute} component={Game}/>
            <Route path={downloadRoute} component={Download}/>
            <Route path="*" component={NotFound}/>
        </Router>

        <Footer>
            <FooterButton route={aboutRoute}>ABOUT</FooterButton>
            <FooterButton route={impressumRoute}>IMPRESSUM</FooterButton>
            <FooterButton route={privacyPolicyRoute}>PRIVACY POLICY</FooterButton>
            <FooterButton onClick={openEmail}>SUPPORT</FooterButton>
        </Footer>
    </div>
</main>

<style>
    .mobile {
        overflow-x: hidden;
    }

    #flex-wrapper {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
        justify-content: space-between;
    }
</style>

// react/src/App.tsx
import "./App.css";
import React, { ReactElement, useEffect } from "react";
import { useApp } from "./lib/AppProvider";
import { Route, Routes, useNavigate } from "react-router-dom";
import Home from "./pages/Home";
import News from "./pages/News";
import Game from "./pages/Game";
import Download from "./pages/Download";
import NavBar from "./lib/NavBar/NavBar";
import NavBarButton from "./lib/NavBar/NavBarButton";
import classnames from "classnames";

const defaultPixelRatio = 16 / 9;

function App(): ReactElement {
    const { isMobile, setMobile } = useApp();
    const navigate = useNavigate();

    useEffect(() => {
        window.onresize = () => {
            const pixelRatio = screen.width / screen.height;
            const mobileThreshold = 1 - (
                0.4 / defaultPixelRatio * pixelRatio);

            if (window.innerWidth <= screen.width * mobileThreshold ||
                window.matchMedia("screen and (max-device-width: 1000px)").matches) {
                setMobile(true);
            } else {
                setMobile(false);
            }
        };
    }, []);

    const homeRoute = "/";
    const newsRoute = "/news";
    const gameRoute = "/game";
    const downloadRoute = "/download";

    const goToHome = () => navigate(homeRoute);
    const goToNews = () => navigate(newsRoute);
    const goToGame = () => navigate(gameRoute);
    const goToDownload = () => navigate(downloadRoute);
    const goToForums = () => window.open("https://" + window.location.host + "/forums/");

    const mainClassName = classnames({ mobile: isMobile });

    return (
        <main className={mainClassName}>
            <NavBar onHomeClick={goToHome}>
                <NavBarButton onClick={goToNews} text="NEWS"/>
                <NavBarButton onClick={goToGame} text="GAME"/>
                <NavBarButton onClick={goToForums} text="FORUMS"/>
                <NavBarButton onClick={goToDownload} text="DOWNLOAD"/>
            </NavBar>

            <Routes>
                <Route path={homeRoute} element={<Home/>}/>
                <Route path={newsRoute} element={<News/>}/>
                <Route path={gameRoute} element={<Game/>}/>
                <Route path={downloadRoute} element={<Download/>}/>
            </Routes>
        </main>
    );
}

export default App;
